"use client";

import React, { useState, useEffect, useCallback, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useAuth } from "@/contexts/AuthContext";
import { useModals } from "@/contexts/ModalContext";
import BaseLayout from "@/components/BaseLayout";
import { WorkflowBuilder } from "@/components/WorkflowBuilder";
import { ChatInput } from "@x402jobs/ui/chat-input";
import { Button } from "@x402jobs/ui/button";
import { Card } from "@x402jobs/ui/card";
import { Input } from "@x402jobs/ui/input";
import { Alert, AlertDescription } from "@x402jobs/ui/alert";
import { Tooltip } from "@x402jobs/ui/tooltip";
import { ChainIcon } from "@/components/icons/ChainIcons";
import type { NetworkType } from "@/hooks/useWorkflowPersistence";
import {
  useGenerateWorkflowProposalMutation,
  type ProposalResponse,
  type GenerateError,
  type Clarification,
} from "@/hooks/useGenerateWorkflowProposalMutation";
import { useCreateWorkflowJobMutation } from "@/hooks/useCreateWorkflowJobMutation";
import { formatUsd } from "@/lib/format";
import {
  AlertCircle,
  Loader2,
  ExternalLink,
  Info,
  ArrowLeft,
  Sparkles,
  MessageSquare,
} from "lucide-react";

interface InputReference {
  type: "reference";
  sourceNodeId: string;
  sourceField: string;
}

interface WorkflowStep {
  order: number;
  resourceId: string;
  resourceName: string;
  resourceSlug?: string;
  resourceUrl: string;
  price: number;
  purpose: string;
  serverId?: string;
  serverName?: string;
  serverSlug?: string;
  outputSchema?: Record<string, unknown>;
  inputMapping?: Record<string, string | InputReference>;
}

/**
 * Format step resource path as server-slug/resource-slug
 */
function formatStepPath(step: WorkflowStep): string {
  if (step.serverSlug && step.resourceSlug) {
    return `${step.serverSlug}/${step.resourceSlug}`;
  }

  try {
    const url = new URL(step.resourceUrl);
    const serverHost = url.hostname;
    const pathParts = url.pathname.split("/").filter(Boolean);
    const resourceSlug = pathParts[pathParts.length - 1] || pathParts.join("/");

    return `${step.serverSlug || serverHost}/${step.resourceSlug || resourceSlug}`;
  } catch {
    return step.resourceName;
  }
}

/**
 * Format field name to display label (outbound_date -> Outbound Date)
 */
function formatFieldLabel(fieldName: string): string {
  return fieldName
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function CreatePageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user, loading: authLoading } = useAuth();
  const { openResourceModal } = useModals();
  const isAuthenticated = !!user;

  // Query params
  const initialPrompt = searchParams.get("prompt") || "";
  const initialName = searchParams.get("name") || "";
  const initialNetwork =
    (searchParams.get("network") as NetworkType) || "solana";
  const useConversational = searchParams.get("mode") === "chat";

  // Mutation hooks
  const {
    generateProposal,
    isGenerating,
    error: generateError,
    clearError: clearGenerateError,
  } = useGenerateWorkflowProposalMutation();
  const {
    createFromProposal,
    isCreating,
    error: createError,
    clearError: clearCreateError,
  } = useCreateWorkflowJobMutation();

  // State
  const [prompt, setPrompt] = useState(initialPrompt);
  const [jobName, setJobName] = useState(initialName);
  const [network, setNetwork] = useState<NetworkType>(initialNetwork);
  const [proposal, setProposal] = useState<ProposalResponse | null>(null);
  const [editedValues, setEditedValues] = useState<Record<string, string>>({});
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Combine errors
  const displayError: GenerateError | null = generateError
    ? generateError
    : createError
      ? { message: createError }
      : null;

  // Get clarifications from proposal
  const clarifications = proposal?.proposal.clarifications || [];
  const hasClarifications = clarifications.length > 0;

  // Get the current value for a clarification (edited or original)
  const getClarificationValue = (c: Clarification) => {
    const key = `${c.nodeId}:${c.fieldName}`;
    return editedValues[key] ?? c.inferredValue;
  };

  // Update a clarification value
  const updateClarificationValue = (c: Clarification, value: string) => {
    const key = `${c.nodeId}:${c.fieldName}`;
    setEditedValues((prev) => ({ ...prev, [key]: value }));
  };

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      const returnUrl = encodeURIComponent(
        `/create?prompt=${encodeURIComponent(prompt)}&name=${encodeURIComponent(jobName)}&network=${network}`,
      );
      router.push(`/login?returnUrl=${returnUrl}`);
    }
  }, [authLoading, isAuthenticated, router, prompt, jobName, network]);

  // Auto-generate on mount if prompt is provided
  const handleGenerate = useCallback(
    async (promptText: string) => {
      if (!promptText.trim()) return;

      setProposal(null);
      clearGenerateError();

      try {
        const data = await generateProposal({
          request: promptText.trim(),
          network,
        });
        setProposal(data);
        // Use AI-generated name if user hasn't specified one
        if (!jobName.trim() && data.proposal.name) {
          setJobName(data.proposal.name);
        }
      } catch {
        // Error is already set by the hook
      }
    },
    [generateProposal, network, jobName, clearGenerateError],
  );

  useEffect(() => {
    if (isAuthenticated && initialPrompt && !hasAutoGenerated && !proposal) {
      setHasAutoGenerated(true);
      handleGenerate(initialPrompt);
    }
  }, [
    isAuthenticated,
    initialPrompt,
    hasAutoGenerated,
    proposal,
    handleGenerate,
  ]);

  // Handle prompt submission
  const handlePromptSubmit = async () => {
    await handleGenerate(prompt);
  };

  // Handle creating job from proposal
  const handleCreateFromProposal = async () => {
    if (!proposal) return;

    clearCreateError();

    try {
      // Apply edited clarification values to the workflow inputs
      const updatedProposal = { ...proposal.proposal };

      // Override name if user provided one
      if (jobName.trim()) {
        updatedProposal.name = jobName.trim();
      }

      if (Object.keys(editedValues).length > 0) {
        updatedProposal.nodes = updatedProposal.nodes.map((node) => {
          if (node.type !== "trigger") return node;

          const nodeData = node.data as {
            workflowInputs?: Array<{
              name: string;
              type: string;
              required: boolean;
              description?: string;
              default?: string;
            }>;
          };

          if (!nodeData.workflowInputs) return node;

          const updatedInputs = nodeData.workflowInputs.map((input) => {
            for (const [key, value] of Object.entries(editedValues)) {
              const fieldName = key.split(":")[1];
              const paramName = fieldName
                .replace(/_/g, " ")
                .replace(/([a-z])([A-Z])/g, "$1 $2")
                .toLowerCase()
                .replace(/\b\w/g, (c) => c.toUpperCase())
                .replace(/\s+/g, "_")
                .toLowerCase();

              if (
                input.name === paramName ||
                input.name.startsWith(paramName)
              ) {
                return { ...input, default: value };
              }
            }
            return input;
          });

          return {
            ...node,
            data: { ...node.data, workflowInputs: updatedInputs },
          };
        });
      }

      const result = await createFromProposal(updatedProposal);
      const jobId = result.job?.id;

      if (jobId) {
        router.push(`/jobs/${jobId}`);
      }
    } catch {
      // Error is already set by the hook
    }
  };

  // Clear proposal and start over
  const handleStartOver = () => {
    setProposal(null);
    setEditedValues({});
    clearGenerateError();
    clearCreateError();
    setPrompt("");
    setJobName("");
  };

  // Handle clicking on a step to view resource details
  const handleStepClick = (step: WorkflowStep) => {
    openResourceModal({
      id: step.resourceId,
      name: step.resourceName,
      slug: step.resourceSlug,
      description: step.purpose,
      resource_url: step.resourceUrl,
      network: proposal?.proposal.network || "solana",
      max_amount_required: String(step.price * 1_000_000),
      server_id: step.serverId,
      server_name: step.serverName,
      server_slug: step.serverSlug,
      output_schema: step.outputSchema,
    });
  };

  // Loading state
  if (authLoading) {
    return (
      <BaseLayout maxWidth="max-w-5xl">
        <div className="min-h-[60vh] flex items-center justify-center">
          <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
        </div>
      </BaseLayout>
    );
  }

  // Conversational chat mode
  if (useConversational) {
    return (
      <WorkflowBuilder
        initialPrompt={initialPrompt}
        initialName={initialName}
        initialNetwork={initialNetwork}
      />
    );
  }

  return (
    <BaseLayout maxWidth="max-w-5xl">
      <div className="py-8 md:py-12">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <button
              onClick={() => router.back()}
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back
            </button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                const params = new URLSearchParams();
                if (prompt) params.set("prompt", prompt);
                if (jobName) params.set("name", jobName);
                params.set("network", network);
                params.set("mode", "chat");
                router.push(`/create?${params.toString()}`);
              }}
              className="gap-2 text-xs"
            >
              <MessageSquare className="w-3.5 h-3.5" />
              Try chat mode
            </Button>
          </div>
          <h1 className="text-2xl md:text-3xl font-bold">Create with AI</h1>
          <p className="text-muted-foreground mt-1">
            Describe what you want to build and AI will generate a workflow for
            you.
          </p>
        </div>

        {/* Show proposal if we have one */}
        {proposal ? (
          <Card className="overflow-hidden">
            {/* Header Section */}
            <div className="p-6 border-b border-border">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-4 h-4 text-primary" />
                    <span className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                      AI-Generated Workflow
                    </span>
                  </div>
                  <input
                    type="text"
                    value={jobName}
                    onChange={(e) => setJobName(e.target.value)}
                    placeholder={proposal.proposal.name}
                    className="text-xl md:text-2xl font-semibold bg-transparent border-none outline-none w-full placeholder:text-foreground/50"
                  />
                  <p className="text-sm text-muted-foreground mt-2 max-w-2xl">
                    {proposal.proposal.description}
                  </p>
                </div>
                <span
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium shrink-0 ${
                    proposal.proposal.network === "base"
                      ? "bg-blue-500/10 text-blue-500"
                      : "bg-purple-500/10 text-purple-500"
                  }`}
                >
                  <ChainIcon
                    network={
                      (proposal.proposal.network as NetworkType) || "solana"
                    }
                    className="w-4 h-4"
                  />
                  {proposal.proposal.network === "base" ? "Base" : "Solana"}
                </span>
              </div>
            </div>

            {/* Parameters Section - Simplified */}
            {hasClarifications && (
              <div className="p-6 border-b border-border bg-muted/30">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                    Parameters
                  </h3>
                </div>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {clarifications.map((c, i) => {
                    const isDate = c.fieldName.toLowerCase().includes("date");
                    return (
                      <div key={i} className="space-y-1.5">
                        <label className="text-sm font-medium text-muted-foreground">
                          {formatFieldLabel(c.fieldName)}
                        </label>
                        <Input
                          type={isDate ? "date" : "text"}
                          value={getClarificationValue(c)}
                          onChange={(e) =>
                            updateClarificationValue(c, e.target.value)
                          }
                          className="bg-background"
                        />
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Workflow Steps Section */}
            <div className="p-6 border-b border-border">
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-4">
                Workflow Steps
              </h3>
              <div className="space-y-2">
                {proposal.proposal.steps.map((step, i) => (
                  <button
                    key={i}
                    onClick={() => handleStepClick(step)}
                    className="w-full flex items-center gap-4 p-3 rounded-lg border border-border bg-background hover:bg-accent transition-colors text-left group"
                  >
                    <div className="w-8 h-8 rounded-lg bg-primary/10 text-primary text-sm font-semibold flex items-center justify-center shrink-0">
                      {step.order}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-mono text-sm truncate group-hover:text-primary transition-colors">
                        {formatStepPath(step)}
                      </p>
                    </div>
                    <ExternalLink className="w-4 h-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity shrink-0" />
                    <span className="text-sm font-medium text-muted-foreground shrink-0">
                      {formatUsd(step.price)}
                    </span>
                  </button>
                ))}
              </div>
            </div>

            {/* Footer Section */}
            <div className="p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <span>Estimated cost per run:</span>
                <span className="font-semibold text-foreground">
                  {formatUsd(proposal.proposal.estimatedCost)}
                </span>
                <Tooltip content="You're only charged when the job runs. Creating jobs is free.">
                  <Info className="w-4 h-4 cursor-help" />
                </Tooltip>
              </div>
              <div className="flex items-center gap-3 w-full sm:w-auto">
                <Button
                  variant="ghost"
                  onClick={handleStartOver}
                  disabled={isCreating}
                  className="flex-1 sm:flex-none"
                >
                  Start Over
                </Button>
                <Button
                  onClick={handleCreateFromProposal}
                  disabled={isCreating}
                  variant="primary"
                  className="gap-2 flex-1 sm:flex-none"
                  size="lg"
                >
                  {isCreating && <Loader2 className="w-4 h-4 animate-spin" />}
                  Create Job
                </Button>
              </div>
            </div>

            {/* Error */}
            {displayError && (
              <div className="p-6 pt-0">
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    <p>{displayError.message}</p>
                    {displayError.suggestion && (
                      <p className="text-muted-foreground mt-1 text-xs">
                        {displayError.suggestion}
                      </p>
                    )}
                  </AlertDescription>
                </Alert>
              </div>
            )}
          </Card>
        ) : (
          /* Input Form */
          <div className="space-y-6">
            {/* Network Selection */}
            <div className="flex items-center gap-4">
              <span className="text-sm text-muted-foreground">Network:</span>
              <div className="flex items-center gap-2">
                {(["solana", "base"] as const).map((net) => (
                  <button
                    key={net}
                    type="button"
                    onClick={() => setNetwork(net)}
                    disabled={isGenerating}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg border transition-all ${
                      network === net
                        ? "border-primary bg-primary/5 text-foreground"
                        : "border-border bg-background text-muted-foreground hover:bg-accent"
                    }`}
                  >
                    <ChainIcon network={net} className="w-4 h-4" />
                    <span className="text-sm font-medium capitalize">
                      {net}
                    </span>
                  </button>
                ))}
              </div>
            </div>

            {/* Prompt Input */}
            <Card className="p-6">
              <ChatInput
                value={prompt}
                onChange={setPrompt}
                onSubmit={handlePromptSubmit}
                placeholder="e.g., Book flights from JFK to Bali departing January 10th returning January 17th"
                isLoading={isGenerating}
                disabled={isGenerating}
                gradientBorder
                className="shadow-lg shadow-primary/10 [&_textarea]:text-base [&_textarea]:py-4 [&_textarea]:min-h-[80px]"
              />

              {isGenerating && (
                <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground py-6">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>
                    Finding matching resources and building your workflow...
                  </span>
                </div>
              )}
            </Card>

            {/* Error */}
            {displayError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>
                  <p>{displayError.message}</p>
                  {displayError.suggestion && (
                    <p className="text-muted-foreground mt-1 text-xs">
                      {displayError.suggestion}
                    </p>
                  )}
                </AlertDescription>
              </Alert>
            )}

            {/* Example prompts */}
            <div>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-3">
                Try these examples
              </p>
              <div className="flex flex-wrap gap-2">
                {[
                  "Book a flight JFK → Bali, Jan 10-17",
                  "Generate an image and turn it into a video",
                  "Generate a profile picture from a CA",
                ].map((example) => (
                  <button
                    key={example}
                    onClick={() => setPrompt(example)}
                    className="px-3 py-1.5 text-sm text-muted-foreground hover:text-foreground bg-muted hover:bg-accent rounded-full transition-colors"
                  >
                    {example}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </BaseLayout>
  );
}

// Wrap in Suspense for useSearchParams
export default function CreatePage() {
  return (
    <Suspense
      fallback={
        <BaseLayout maxWidth="max-w-5xl">
          <div className="min-h-[60vh] flex items-center justify-center">
            <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
          </div>
        </BaseLayout>
      }
    >
      <CreatePageContent />
    </Suspense>
  );
}
